In [24]:
import pandas as pd

In [46]:
marathon = pd.read_csv("half_marathon.csv")
marathon.head(15)

                 Jmeno  Rocnik       Cas  Rok zavodu
0       Aster Vladimír    1965  01:53:25        2019
1       Aster Vladimír    1965  02:00:19        2020
2        Asterová Jana    1974  02:16:59        2019
3        Asterová Jana    1974  02:30:01        2020
4        Baborová Anna    1990  01:58:20        2019
5        Baborová Anna    1990  01:52:25        2020
6           Bambas Jan    1975  02:02:59        2019
7           Bambas Jan    1975  02:35:39        2020
8   Barochovská Andrea    1976  03:01:25        2019
9   Barochovská Andrea    1976  02:50:05        2020
10        Bartl Matouš    1984  02:17:43        2019
11        Bartl Matouš    1984  02:45:32        2020
12        Bartošek Jan    1985  02:05:56        2019
13        Bartošek Jan    1985  02:07:25        2020
14    Bartošková Lucie    1993  02:08:55        2019

In [50]:
marathon["Cas_shift"] = marathon["Cas"].shift(periods=1)
marathon["Rok zavodu"] = 2020;
marathon

                  Jmeno  Rocnik       Cas  Rok zavodu Cas_shift
1        Aster Vladimír    1965  02:00:19        2020      None
3         Asterová Jana    1974  02:30:01        2020  02:00:19
5         Baborová Anna    1990  01:52:25        2020  02:30:01
7            Bambas Jan    1975  02:35:39        2020  01:52:25
9    Barochovská Andrea    1976  02:50:05        2020  02:35:39
..                  ...     ...       ...         ...       ...
180       Šulcová Jitka    1974  01:59:07        2020  02:13:40
182      Švarcová Petra    1974  02:50:01        2020  01:59:07
184        Švelch Rosťa    1966  01:55:11        2020  02:50:01
186        Žitková Jana    1974  02:42:48        2020  01:55:11
188       Žákovec Pavel    1966  02:07:37        2020  02:42:48

[95 rows x 5 columns]

In [54]:
marathon["Cas"] = pd.to_date(marathon["Cas"])
marathon["Cas2"] = pd.to_date(marathon["Cas"]).shift(-1)

AttributeError: module 'pandas' has no attribute 'to_date'

In [55]:
marathon = marathon[marathon["Rok zavodu"] == 2020].copy()
marathon["diff"] = marathon ["Cas"] - marathon["Cas2"] 
marathon["diff"] = marathon["diff"].dt.total_seconds()
marathon["diff"].mean()

KeyError: 'Cas2'